{{/*
Expand the name of the chart.
*/}}
{{- define "homepage.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
A "fullname" prefix used by every resource. Honors fullnameOverride and falls
back to "<release>-<chart>", so two releases can coexist in one namespace.
*/}}
{{- define "homepage.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Common labels shared by every object. The name/instance pair is what
`kubectl logs -l app.kubernetes.io/instance=<release>` keys off.
*/}}
{{- define "homepage.labels" -}}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
app.kubernetes.io/name: {{ include "homepage.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ include "homepage.tag" . | trunc 63 | trimSuffix "-" | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end -}}

{{/*
Selector labels. Deliberately excludes version and chart: Kubernetes rejects
mutating a Deployment's selector, so anything that changes on upgrade cannot
live here.
*/}}
{{- define "homepage.selectorLabels" -}}
app.kubernetes.io/name: {{ include "homepage.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{/*
Explicit tag wins, then Chart.AppVersion, so an unconfigured chart still pulls
a matching release.
*/}}
{{- define "homepage.tag" -}}
{{- default .Chart.AppVersion .Values.image.tag -}}
{{- end -}}

{{- define "homepage.image" -}}
{{- $reg := .Values.image.registry | default "docker.io" -}}
{{- printf "%s/%s:%s" $reg .Values.image.repository (include "homepage.tag" .) -}}
{{- end -}}

{{/*
The Secret holding ARGUS_KEY, whether generated by this chart or supplied by
the user.
*/}}
{{- define "homepage.secretName" -}}
{{- .Values.argus.existingSecret | default (include "homepage.fullname" .) -}}
{{- end -}}

{{/*
existingSecretKey renames the key only in a Secret managed elsewhere; the
generated one always writes ARGUS_KEY.
*/}}
{{- define "homepage.secretKey" -}}
{{- if .Values.argus.existingSecret -}}
{{- .Values.argus.existingSecretKey | default "ARGUS_KEY" -}}
{{- else -}}
ARGUS_KEY
{{- end -}}
{{- end -}}

{{/*
Whether the wall boards are wired at all. Running without Argus is a supported
mode, so this decides what gets rendered rather than whether to fail.
*/}}
{{- define "homepage.argusConfigured" -}}
{{- if .Values.argus.url -}}
true
{{- end -}}
{{- end -}}

{{/*
Fail early with a readable message rather than rendering something half broken.

A URL without a key, or a key without a URL, still installs and runs: the
server logs one line and /api/pixels answers 502 forever. That looks exactly
like an Argus outage, so it is refused here instead.
*/}}
{{- define "homepage.validate" -}}
{{- $hasKey := or .Values.argus.apiKey .Values.argus.existingSecret -}}
{{- if and .Values.argus.apiKey .Values.argus.existingSecret -}}
{{- fail "Set either argus.apiKey or argus.existingSecret, not both." -}}
{{- end -}}
{{- if and .Values.argus.url (not $hasKey) -}}
{{- fail "argus.url is set but there is no key. Set argus.apiKey, or point argus.existingSecret at a Secret carrying ARGUS_KEY." -}}
{{- end -}}
{{- if and $hasKey (not .Values.argus.url) -}}
{{- fail "An Argus key is configured but argus.url is empty, so it would never be used. Set argus.url, or clear the key to run with the boards unlit." -}}
{{- end -}}
{{- if and .Values.argus.url (not (regexMatch "^https?://" .Values.argus.url)) -}}
{{- fail (printf "argus.url must start with http:// or https://, got %q." .Values.argus.url) -}}
{{- end -}}
{{- if and .Values.ingress.enabled (not .Values.ingress.hosts) -}}
{{- fail "ingress.enabled is true but ingress.hosts is empty." -}}
{{- end -}}
{{- end -}}
